export const examplePhrases = [
  "una carpa de circo abandonada",
  "un bosque encantado al amanecer",
  "la biblioteca secreta de un castillo",
  "un mercado flotante en otro planeta",
  "el último tren antes del fin del mundo",
  "una ciudad sumergida bajo el mar",
  "el laboratorio de un alquimista loco",
  "una nave espacial perdida en el tiempo",
  "el jardín de estatuas vivientes",
  "una taberna en la cima de una montaña",
  "el circo de criaturas mágicas",
  "un pueblo donde nunca anochece",
  "el museo de objetos imposibles",
  "una estación de tren fantasma",
  "el mercado de sueños usados",
  "una biblioteca donde los libros hablan",
  "el faro en el fin del mundo",
  "una isla que aparece solo de noche",
  "el teatro de marionetas sin hilos",
  "una fábrica de juguetes olvidados",
  "el bosque donde los árboles caminan",
  "una ciudad en el interior de una montaña",
  "el castillo de los relojes rotos",
  "un tren que viaja entre dimensiones",
  "el café de los viajeros del tiempo",
  "una playa donde nunca sale el sol",
  "el parque de atracciones abandonado",
  "una cueva de cristales cantores",
  "el pueblo de los gatos parlantes",
  "una torre que toca las nubes",
  "el mercado de los recuerdos perdidos",
  "una casa que cambia de lugar cada noche",
  "el jardín de las flores invisibles",
  "una biblioteca bajo tierra",
  "el circo de los sueños rotos",
  "una isla flotante en el cielo",
  "el teatro de sombras vivientes",
  "una ciudad donde todos vuelan",
  "el museo de los monstruos amables",
  "una estación espacial olvidada",
  "el bosque de los espejos mágicos",
  "una taberna en el fondo del mar",
  "el castillo de los susurros",
  "una fábrica de caramelos eternos",
  "el mercado de los objetos imposibles",
  "una cueva donde el tiempo se detiene",
  "el pueblo de los relojes sin manecillas",
  "una playa de arena azul",
  "el jardín de los árboles de cristal",
  "una ciudad donde nunca llueve",
  "el teatro de los sueños perdidos",
  "una biblioteca de mapas infinitos",
  "el faro de los navegantes perdidos",
  "una isla de dragones dormidos",
  "el café de los poetas olvidados",
  "una casa en el borde del abismo",
  "el parque de los columpios voladores",
  "una cueva de luces danzantes",
  "el pueblo de los fantasmas alegres",
  "una torre de relojes gigantes",
  "el mercado de los colores prohibidos",
  "una ciudad de puentes infinitos",
  "el jardín de los pájaros de fuego",
  "una biblioteca de historias sin fin",
  "el circo de los animales invisibles",
  "una isla de volcanes cantores",
  "el teatro de los actores mudos",
  "una estación de tren bajo el mar",
  "el castillo de los dragones de papel",
  "una fábrica de sueños embotellados",
  "el bosque de los susurros eternos",
  "una taberna de piratas fantasmas",
  "el mercado de los relojes de arena",
  "una casa de puertas infinitas",
  "el jardín de los peces voladores",
  "una ciudad de luces flotantes",
  "el museo de los recuerdos felices",
  "una estación espacial de robots olvidados",
  "el teatro de los magos dormidos",
  "una isla de árboles dorados",
  "el café de los viajeros nocturnos",
  "una cueva de mariposas luminosas",
  "el pueblo de los niños eternos",
  "una torre de libros infinitos",
  "el mercado de los susurros secretos",
  "una ciudad de ventanas parlantes",
  "el jardín de los relojes de agua",
  "una biblioteca de canciones perdidas",
  "el circo de los payasos tristes",
  "una isla de pájaros gigantes",
  "el teatro de los autómatas alegres",
  "una estación de tren en el desierto",
  "el castillo de los espejos rotos",
  "una fábrica de marionetas mágicas",
  "el bosque de los árboles de fuego",
  "una taberna de viajeros del tiempo",
  "el mercado de los objetos olvidados",
  "una casa de ventanas infinitas",
  "el jardín de los gatos invisibles",
  "una ciudad de puentes de cristal",
  "el museo de los monstruos dormidos"
];
